### ISSUE TITLE
[12,13][BUG] base_tier_validation, for case sequence approval

### ISSUE THREAD

**Issue by kittiu** [OCA/server-ux#195]
I have tested approval by sequence, for 3 steps approval. Where step 1 and 3 is by **user1**, and step 2 is for **user2**

I would expect that, it will run by sequence no matter what. But when user1 approve, it result like this.

![image](https://user-images.githubusercontent.com/1973598/91408024-5d24e600-e86d-11ea-86df-346d77560dbc.png)

I understand that it might seem like a feature, because without sequence approval, when a user approve, all steps by that users will get approved.

But I still think, it will be more intuitative in case approval by sequence, to go one step at a time only. @ps-tubtim , can you fix?

cc @LoisRForgeFlow WDYT?

**Comment by kittiu** [comment]
Fixed here, https://github.com/OCA/server-ux/pull/198

**Comment by nmoturi** [comment]
I tested the sequence flow, but for me it seems to be still a problem how the approval chain needed to cascade when seq is defined.

Here is the screenshot, I was expecting when a sequence is defined for the same validation the review seq's counter needs to be as per the seq flow. In the example shown below I was able to validate the higher review seq first and the rest later..

Not sure if this is a desired outcome if yes, whats the use of "Approve by sequence" option in the definition..
![image](https://user-images.githubusercontent.com/7597063/92319453-a807e000-f05b-11ea-80f6-f8e2dfa8cde9.png)

Thanks,
Naran
